= My Experiment
:author: Axel Sorenson
:date: 2025-11-26

test test test.

This plot is generated at build time by a simple script:

image::generated/plot.svg[Experiment plot]

== Runnable WASM demo

+++
<div id="wasm-demo">
  <pre id="wasm-output">Output will appear here.</pre>
  <button id="wasm-run">Run WASM</button>
  <script src="wasm/wasm-loader.js?v=3"></script>
</div>
+++

== Embedded JSON

+++
<pre id="json-data">Loading…</pre>
<script>
fetch('generated/data.json').then(r=>r.json()).then(j=>{
  document.getElementById('json-data').textContent = JSON.stringify(j, null, 2);
})
 </script>
 +++

== Rust Code Sample

[source,rust]
----
// Simple Rust example to demonstrate syntax highlighting
fn main() {
    let nums = [1, 2, 3, 5, 8, 13];
    let sum: i32 = nums.iter().sum();
    println!("Sum is {}", sum);
}
----

== Latex Test

.Finite automaton
image::generated/automaton.svg[width=60%]

== Typst Test
image::generated/complex-plane.svg[width=60%]

== Lambda Reduction Cube
There are 3 axes:

* Redex Selection
** Outermost (leftmost-outermost)
** Innermost (leftmost-innermost)
* λ-Restriction
** Unrestricted (reduction under lambda abstractions allowed)
** Abstraction-restricted (reduction under lambda abstractions now allowed)
* β-Restriction (What is considered a redex)
** Unrestricted (arguments to an application don't have to be a value)
** Value-restricted (arguments to an application have to be a value)

Key:

* λNO: Normal-Order reduction
* λAO: Applicative-Order reduction
* λCBN: Call-By-Name reduction (the same as Weak Normal-Order reduction)
* λCBV: Call-By-Value reduction
* λWAO: Weak Applicative-Order reduction
* λWNO: Weak Normal-Order reduction (the same as Call-By-Name reduction)

.Cube
image::generated/cube.svg

Please note - selection and λ-restriction (also known as strong and weak) are
common in literature. In fact, most of the time Call-By-Value is considered the same
as Weak Applicative Order. Selection and λ-restriction are positional in nature,
with one determining which redex to contract first and the other blocking some
redexes from being contracted. β-Restriction is different, in that it also
determines what _is_ a redex to begin with. β-Restricted evaluation simply says
that (λx.M) N is not a redex if N is not a value.
