= My Experiment
:author: Axel Sorenson
:date: 2025-11-26

test test test.

This plot is generated at build time by a simple script:

image::generated/plot.svg[Experiment plot]

== Runnable WASM demo

+++
<div id="wasm-demo">
  <pre id="wasm-output">Output will appear here.</pre>
  <button id="wasm-run">Run WASM</button>
  <script src="wasm/wasm-loader.js?v=3"></script>
</div>
+++

== Embedded JSON

+++
<pre id="json-data">Loading…</pre>
<script>
fetch('generated/data.json').then(r=>r.json()).then(j=>{
  document.getElementById('json-data').textContent = JSON.stringify(j, null, 2);
})
 </script>
 +++

== Rust Code Sample

[source,rust]
----
// Simple Rust example to demonstrate syntax highlighting
fn main() {
    let nums = [1, 2, 3, 5, 8, 13];
    let sum: i32 = nums.iter().sum();
    println!("Sum is {}", sum);
}
----

== Latex Test

.Finite automaton
image::generated/automaton.svg[width=60%]

== Typst Test
image::generated/complex-plane.svg[width=60%]

== Lambda Reduction Cube
There are 3 axes:

* Redex Selection
** Outermost (leftmost-outermost)
** Innermost (leftmost-innermost)
* λ-Strength
** Unrestricted (reduction under lambda abstractions allowed)
** Abstraction-restricted (reduction under lambda abstractions now allowed)
* β-restriction
** Unrestricted (arguments to an application don't have to be a value)
** Value-restricted (arguments to an application have to be a value)

Key:

* λNO: Normal-Order reduction
* λAO: Applicative-Order reduction
* λCBN: Call-By-Name reduction (the same as Weak Normal-Order reduction)
* λCBVₘ: Call-By-Value reduction (For machines)
* λCBVᵣ: Call-By-Value reduction (For redexes)
* λWAO: Weak Applicative-Order reduction
* λWNO: Weak Normal-Order reduction (the same as Call-By-Name reduction)

.Cube
image::generated/cube.svg