#!/usr/bin/env python3
"""Generate sched_data.py for the scheduler animations, from the real traces.

The animations must not carry hand-typed constants: every consumer position,
budget floor, fragment width and issue point below comes out of the same two
logs that produced lifelines-canonical.png, so the videos and the plots cannot
disagree.

Emits, for each fragment the mutation CLAMPS (the dark-blue bars in the
lifelines chart):
    cmin, cmax   first / last consuming WMMA index
    vgprs        fragment width (a vreg_512 is 16; the scale loads are 2)
    floor        earliest WMMA the RP budget allows it to issue after
    issue_off    WMMA index it was actually issued at, mutation OFF
    issue_on     ... and mutation ON

Usage:
  extract-anim-data.py <nomut.log> <mut.log> [-o sched_data.py]
"""
import argparse
import importlib.util
import os
from collections import Counter

REPRO = "/home/asorenso/work/gfx1250/repro"


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, os.path.join(REPRO, path))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


st = _load("sched_tape", "sched-tape.py")
el = _load("early_loads", "early-loads.py")


def scan(path):
    """-> (region, frags{su:info}, issue{su: wmma index when issued})"""
    per = el.parse_mutation(path)
    t = st.Tape()
    t.feed(open(path, errors="replace"))
    t.finish()
    byreg = Counter(r["region"] for r in t.rows if st.kind(r["op"]) == "wmma")
    # the FIRST region with the most WMMAs: a later stage re-schedules it and
    # renumbers the SUs, so mixing regions would silently mismatch fragments.
    region = min(rg for rg, n in byreg.items() if n == max(byreg.values()))
    _minpos, frags, _budget = per[region]

    # `w` counts WMMAs scheduled so far, but `floor` from the pass is a WMMA
    # INDEX -- once W[59] has issued the count is 60. Record the index of the
    # last WMMA scheduled before the load, so issue points and budget floors are
    # the same kind of number and can be compared (and printed) directly.
    w, issue = 0, {}
    for r in (x for x in t.rows if x["region"] == region):
        k = st.kind(r["op"])
        if k == "wmma":
            w += 1
        elif k == "ds" and r["su"] not in issue:
            issue[r["su"]] = max(0, w - 1)
    return frags, issue


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("nomut")
    ap.add_argument("mut")
    ap.add_argument("-o", "--out", default="sched_data.py")
    ap.add_argument("--kernel", default="mxfp_gemm_canonical_32t")
    a = ap.parse_args()

    frags_off, issue_off = scan(a.nomut)
    frags_on, issue_on = scan(a.mut)

    # one entry per clamped fragment, keyed by its subload tuple
    seen, rows = set(), []
    for su, f in frags_on.items():
        key = tuple(f["subs"])
        if key in seen or not f["clamped"]:
            continue
        seen.add(key)
        off = [issue_off[s] for s in f["subs"] if s in issue_off]
        on = [issue_on[s] for s in f["subs"] if s in issue_on]
        if not off or not on:
            continue
        rows.append(dict(cmin=f["cmin"], cmax=f["cmax"], vgprs=f["vgprs"],
                         floor=f["floor"], issue_off=min(off), issue_on=min(on),
                         subs=list(key)))
    rows.sort(key=lambda r: (r["issue_on"], r["cmin"]))

    fields = ["cmin", "cmax", "vgprs", "floor", "issue_off", "issue_on"]
    if a.out.endswith(".json"):
        import json
        with open(a.out, "w") as fh:
            json.dump(dict(kernel=a.kernel, wmax=127,
                           clamped=[{k: r[k] for k in fields} for r in rows]),
                      fh, separators=(",", ":"))
            fh.write("\n")
    else:
        with open(a.out, "w") as fh:
            fh.write('"""GENERATED by extract-anim-data.py -- do not edit by hand.\n\n'
                     'Fragments the WMMA DAG mutation clamps (the dark-blue bars in\n'
                     'lifelines-*.png), with the WMMA index each was issued at with the\n'
                     'mutation off and on. Everything here is parsed from the scheduler\n'
                     'and mutation debug streams; nothing is hand-tuned.\n"""\n')
            fh.write(f"KERNEL = {a.kernel!r}\n")
            fh.write(f"WMAX = 127\n")
            fh.write("CLAMPED = [\n")
            for r in rows:
                fh.write("    dict(" + ", ".join(f"{k}={r[k]!r}" for k in fields) + "),\n")
            fh.write("]\n")
    print(f"wrote {len(rows)} clamped fragments -> {a.out}")
    print(f"{'cmin':>5}{'cmax':>6}{'vgpr':>6}{'floor':>7}{'off':>6}{'on':>5}")
    for r in rows:
        print(f"{r['cmin']:>5}{r['cmax']:>6}{r['vgprs']:>6}{r['floor']:>7}"
              f"{r['issue_off']:>6}{r['issue_on']:>5}")
    tot = sum(r["vgprs"] for r in rows)
    print(f"total clamped VGPRs: {tot}")


if __name__ == "__main__":
    main()
